#!/usr/bin/env bash
set -euo pipefail

REPO="${DB_IMAGE_REPO:-ghcr.io/agustin-gigena/enigma-dev-db}"
WORKSPACE="${WORKSPACE_FOLDER:-/workspaces/Enigma}"
LOG_DIR="$HOME/.devcontainer/dev-logs"
mkdir -p "$LOG_DIR"

cd "$WORKSPACE"

# --- Idempotency: tear down previous session's processes first. ---
docker rm -f enigma-dev-db >/dev/null 2>&1 || true
pkill -f 'dotnet watch --project Server' >/dev/null 2>&1 || true
pkill -f 'dotnet watch --project Client' >/dev/null 2>&1 || true

# --- 1. Resolve the nearest long-lived ancestor that has a published image tag. ---
LONG_BRANCH=""
for ref in $(git rev-list --first-parent --simplify-merges HEAD); do
  for cand in production development; do
    if git merge-base --is-ancestor "$ref" "origin/$cand" 2>/dev/null; then
      LONG_BRANCH="$cand"
      break
    fi
  done
  [ -n "$LONG_BRANCH" ] && break
done

if [ -z "$LONG_BRANCH" ]; then
  echo "dev: no production/development ancestor for $(git rev-parse --abbrev-ref HEAD); defaulting to 'development'." >&2
  LONG_BRANCH=development
fi

IMAGE="$REPO:$LONG_BRANCH"
echo "dev: using $IMAGE for MySQL"

# --- 1b. Configure the dev environment: write a workspace .env and export its vars. ---
ENV_FILE="$WORKSPACE/.env"
cat >"$ENV_FILE" <<EOF
# Generated by .devcontainer/start-dev.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
ASPNETCORE_ENVIRONMENT=Development
ASPNETCORE_URLS=http://localhost:8080

# Blazor WASM dev server (Client) listens via launchSettings.json; this var just hints the env.
ASPNETCORE_CLIENT_URLS=http://localhost:80;https://localhost:443

# MySQL connection (matches the docker run below and appsettings.json interpolation).
MYSQL_HOST=localhost
MYSQL_PORT=3306
MYSQL_DATABASE=$MYSQL_DATABASE
MYSQL_USER=$MYSQL_USER
MYSQL_PASSWORD=$MYSQL_PASSWORD
MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

# Dev DB image selection (for manual re-runs of the launcher).
DB_IMAGE_REPO=$REPO
DB_IMAGE_TAG=$LONG_BRANCH
EOF
set -a
. "$ENV_FILE"
set +a
echo "dev: wrote $ENV_FILE and exported dev vars"

# --- 2. Wait for the DinD daemon (started by the docker-in-docker feature). ---
for _ in $(seq 1 30); do docker info >/dev/null 2>&1 && break; sleep 1; done

# --- 3. Pull + run MySQL; volume keyed by tag (per-branch DB state). ---
docker pull "$IMAGE"
docker run -d --rm \
  --name enigma-dev-db \
  -p 3306:3306 \
  -e MYSQL_ROOT_PASSWORD="$MYSQL_ROOT_PASSWORD" \
  -e MYSQL_USER="$MYSQL_USER" \
  -e MYSQL_PASSWORD="$MYSQL_PASSWORD" \
  -e MYSQL_DATABASE="$MYSQL_DATABASE" \
  -v "enigma-dev-db-${LONG_BRANCH}-data:/var/lib/mysql" \
  "$IMAGE"

# Wait for MySQL to accept connections before starting Server.
for _ in $(seq 1 60); do
  docker exec enigma-dev-db mysqladmin ping -h localhost -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" >/dev/null 2>&1 && break
  sleep 1
done
echo "dev: MySQL alive at localhost:3306 (tag $LONG_BRANCH)"

# --- 4. Start Server and Client in watch under nohup; ports via launchSettings.json. ---
nohup dotnet watch --project Server >"$LOG_DIR/server.log" 2>&1 &
echo "dev: Server watch started (see $LOG_DIR/server.log)"

# Small delay so the Server dev certificate / port reservation finishes first.
sleep 2

nohup dotnet watch --project Client >"$LOG_DIR/client.log" 2>&1 &
echo "dev: Client watch started (see $LOG_DIR/client.log)"

echo "dev: full stack up — MySQL :3306 | Server :8080 | Client :80/:443"
