#!/usr/bin/env bash
set -euo pipefail

REPO="${DB_IMAGE_REPO:-ghcr.io/agustin-gigena/enigma-dev-db}"
WORKSPACE="${WORKSPACE_FOLDER:-/workspaces/Enigma}"
LOG_DIR="$HOME/.devcontainer/dev-logs"
mkdir -p "$LOG_DIR"

cd "$WORKSPACE"

# --- Validate required env vars ---
for var in MYSQL_DATABASE MYSQL_USER MYSQL_PASSWORD MYSQL_ROOT_PASSWORD; do
  if [ -z "${!var:-}" ]; then
    echo "ERROR: $var is not set. Provide it via remoteEnv or the environment." >&2
    exit 1
  fi
done

# --- PID tracking and cleanup trap ---
SERVER_PID=""
CLIENT_PID=""
cleanup() {
  echo "dev: cleaning up..." >&2
  [ -n "$CLIENT_PID" ] && kill "$CLIENT_PID" 2>/dev/null || true
  [ -n "$SERVER_PID" ] && kill "$SERVER_PID" 2>/dev/null || true
  docker rm -f enigma-dev-db >/dev/null 2>&1 || true
}
trap cleanup EXIT

# --- Idempotency: tear down previous session's processes first. ---
docker rm -f enigma-dev-db >/dev/null 2>&1 || true
pkill -f 'dotnet watch --project Server' >/dev/null 2>&1 || true
pkill -f 'dotnet watch --project Client' >/dev/null 2>&1 || true

# --- 1. Resolve the nearest long-lived ancestor that has a published image tag. ---
LONG_BRANCH=""
for ref in $(git rev-list --first-parent --simplify-merges HEAD); do
  for cand in production development; do
    if git merge-base --is-ancestor "$ref" "origin/$cand" 2>/dev/null; then
      LONG_BRANCH="$cand"
      break
    fi
  done
  [ -n "$LONG_BRANCH" ] && break
done

if [ -z "$LONG_BRANCH" ]; then
  echo "dev: no production/development ancestor for $(git rev-parse --abbrev-ref HEAD); defaulting to 'development'." >&2
  LONG_BRANCH=development
fi

IMAGE="$REPO:$LONG_BRANCH"
echo "dev: using $IMAGE for MySQL"

# --- 1b. Configure the dev environment: write .env files and export vars. ---
SERVER_ENV="$WORKSPACE/Server/.env"
CLIENT_ENV="$WORKSPACE/Client/.env"

cat >"$SERVER_ENV" <<EOF
# Generated by .devcontainer/start-dev.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
ASPNETCORE_ENVIRONMENT=Development

# MySQL connection (matches docker run and appsettings.json interpolation).
MYSQL_HOST=localhost
MYSQL_PORT=3306
MYSQL_DATABASE=$MYSQL_DATABASE
MYSQL_USER=$MYSQL_USER
MYSQL_PASSWORD=$MYSQL_PASSWORD
MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
EOF

cat >"$CLIENT_ENV" <<EOF
# Generated by .devcontainer/start-dev.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
SERVER_URI=http://localhost:8080
EOF

set -a
. "$SERVER_ENV"
. "$CLIENT_ENV"
set +a
echo "dev: wrote $SERVER_ENV and $CLIENT_ENV, exported dev vars"

# --- 2. Wait for the DinD daemon (started by the docker-in-docker feature). ---
DIND_READY=false
for _ in $(seq 1 30); do
  if docker info >/dev/null 2>&1; then DIND_READY=true; break; fi
  sleep 1
done
if [ "$DIND_READY" != "true" ]; then
  echo "ERROR: Docker daemon not ready after 30s. Check DinD feature." >&2
  exit 1
fi

# --- 3. Pull + run MySQL; volume keyed by tag (per-branch DB state). ---
docker pull "$IMAGE"
docker run -d --rm \
  --name enigma-dev-db \
  -p 3306:3306 \
  -e MYSQL_ROOT_PASSWORD="$MYSQL_ROOT_PASSWORD" \
  -e MYSQL_USER="$MYSQL_USER" \
  -e MYSQL_PASSWORD="$MYSQL_PASSWORD" \
  -e MYSQL_DATABASE="$MYSQL_DATABASE" \
  -v "enigma-dev-db-${LONG_BRANCH}-data:/var/lib/mysql" \
  "$IMAGE"
# Wait for MySQL to accept connections before starting Server.
MYSQL_READY=false
for _ in $(seq 1 60); do
  if docker exec enigma-dev-db mysqladmin ping -h localhost -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" >/dev/null 2>&1; then
    MYSQL_READY=true
    break
  fi
  sleep 1
done
if [ "$MYSQL_READY" != "true" ]; then
  echo "ERROR: MySQL not ready after 60s. Last container logs:" >&2
  docker logs --tail 20 enigma-dev-db >&2
  exit 1
fi
echo "dev: MySQL alive at localhost:3306 (tag $LONG_BRANCH)"

# --- 4. Start Server and Client in watch under nohup; ports via launchSettings.json. ---
nohup dotnet watch --project Server >"$LOG_DIR/server.log" 2>&1 &
SERVER_PID=$!
echo "dev: Server watch started (PID $SERVER_PID, see $LOG_DIR/server.log)"

# Small delay so the Server dev certificate / port reservation finishes first.
sleep 2

nohup dotnet watch --project Client >"$LOG_DIR/client.log" 2>&1 &
CLIENT_PID=$!
echo "dev: Client watch started (PID $CLIENT_PID, see $LOG_DIR/client.log)"

echo "dev: full stack up — MySQL :3306 | Server :8080 | Client :80/:443"
